### ISSUE TITLE
pytextrank.text_rank  -> 'DiGraph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by clayms** [DerwenAI/pytextrank#18]
When trying out the [examples](https://github.com/ceteri/pytextrank/blob/master/example.ipynb), the line `graph, ranks = pytextrank.text_rank(path_stage1)` throws the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 349, in text_rank
    graph = build_graph(json_iter(path))
  File "/home/user/.local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 308, in build_graph    graph.edge[pair[0]][pair[1]]["weight"] += 1.0
AttributeError: 'DiGraph' object has no attribute 'edge'
```

https://github.com/ceteri/pytextrank/blob/181ea41375d29922eb96768cf6550e57a77a0c95/pytextrank/pytextrank.py#L308

Red Hat Enterprise Linux Server release 7.3 (Maipo)
core-4.1-amd64:core-4.1-noarch
python 3.6.4
pytextrank==1.1.0
spacy==2.0.11
graphviz==0.8.3
networkx==2.1
decorator==4.3.0

`path_stage1` file contents:

```
["777", "7b982e54fa330a6854a0ed5397d49223fdc70645", [[1, "Compatibility", "compatibility", "NN", 1, 0], [0, "of", "of", "IN", 0, 1], [2, "systems", "system", "NNS", 1, 2], [0, "of", "of", "IN", 0, 3], [3, "linear", "linear", "JJ", 1, 4], [4, "constraints", "constraint", "NNS", 1, 5], [0, "over", "over", "IN", 0, 6], [0, "the", "the", "DT", 0, 7], [5, "set", "set", "NN", 1, 8], [0, "of", "of", "IN", 0, 9], [6, "natural", "natural", "JJ", 1, 10], [7, "numbers", "number", "NNS", 1, 11], [0, ".", ".", ".", 0, 12]]]
834
["777", "c1cd88e3fec11b0772c6be12b7504f332c0b3d8f", [[8, "Criteria", "criterion", "NNS", 1, 13], [0, "of", "of",
"IN", 0, 14], [1, "compatibility", "compatibility", "NN", 1, 15], [0, "of", "of", "IN", 0, 16], [0, "a", "a", "DT", 0, 17], [2, "system", "system", "NN", 1, 18], [0, "of", "of", "IN", 0, 19], [3, "linear", "linear", "JJ", 1, 20], [9, "Diophantine", "diophantine", "NNP", 1, 21], [10, "equations", "equation", "NNS", 1, 22], [0, ",", ",", ".", 0, 23], [11, "strict", "strict", "JJ", 1, 24], [12, "inequations", "inequation", "NNS", 1, 25], [0, ",", ",", ".", 0, 26], [0, "and", "and", "CC", 0, 27], [13, "nonstrict", "nonstrict", "NN", 1, 28], [12, "inequations", "inequation", "NNS", 1, 29], [14, "are", "be", "VBP", 1, 30], [15, "considered", "consider", "VBN", 1, 31], [0, ".", ".", ".", 0, 32]]]
1093
["777", "cb9235d7c8b21321b88462fca3a0480e29aa8ec7", [[16, "Upper", "upper", "NNP", 1, 33], [17, "bounds", "bound", "VBZ", 1, 34], [0, "for", "for", "IN", 0, 35], [18, "components", "component", "NNS", 1, 36], [0, "of", "of", "IN", 0, 37], [0, "a", "a", "DT", 0, 38], [19, "minimal", "minimal", "JJ", 1, 39], [5, "set", "set", "NN", 1, 40], [0, "of", "of", "IN", 0, 41], [20, "solutions", "solution", "NNS", 1, 42], [0, "and", "and", "CC", 0, 43], [21,
"algorithms", "algorithm", "NNS", 1, 44], [0, "of", "of", "IN", 0, 45], [22, "construction", "construction", "NN", 1, 46], [0, "of", "of", "IN", 0, 47], [19, "minimal", "minimal", "JJ", 1, 48], [23, "generating", "generating", "NN", 1, 49], [5, "sets", "set", "NNS", 1, 50], [0, "of", "of", "IN", 0, 51], [20, "solutions", "solution", "NNS", 1, 52], [0, "for", "for", "IN", 0, 53], [0, "all", "all", "DT", 0, 54], [24, "types", "type", "NNS", 1, 55], [0, "of", "of", "IN", 0, 56], [2, "systems", "system", "NNS", 1, 57], [14, "are", "be", "VBP", 1, 58], [25, "given", "give", "VBN", 1, 59], [0, ".", ".", ".", 0, 60]]]
1179
["777", "ae690a522dbc83b7c8447b5bf863ffa95d681ce0", [[0, "These", "these", "DT", 0, 61], [8, "criteria", "criterion", "NNS", 1, 62], [0, "and", "and", "CC", 0, 63], [0, "the", "the", "DT", 0, 64], [26, "corresponding", "correspond", "VBG", 1, 65], [21, "algorithms", "algorithm", "NNS", 1, 66], [0, "for", "for", "IN", 0, 67], [27, "constructing", "construct", "VBG", 1, 68], [0, "a", "a", "DT", 0, 69], [19, "minimal", "minimal", "JJ", 1, 70], [28, "supporting", "support", "VBG", 1, 71], [5, "set", "set", "NN", 1, 72], [0, "of", "of", "IN", 0, 73], [20, "solutions", "solution", "NNS", 1, 74], [0, "can", "can", "MD", 0, 75], [14, "be", "be", "VB", 1, 76], [29, "used", "use", "VBN", 1, 77], [0, "in", "in", "IN", 0, 78], [30, "solving", "solve", "VBG", 1, 79], [0, "all", "all", "PDT", 0, 80], [0, "the", "the", "DT", 0, 81], [15, "considered", "consider", "VBN", 1, 82], [24, "types", "type", "NNS", 1, 83], [2, "systems", "system", "NNS", 1, 84], [0, "and", "and", "CC", 0, 85], [2, "systems", "system", "NNS",
1, 86], [0, "of", "of", "IN", 0, 87], [31, "mixed", "mixed", "JJ", 1, 88], [24, "types", "type", "NNS", 1, 89], [0, ".", ".", ".", 0, 90]]]
```

**Comment by clayms** [comment]
based on the NetworkX [documentation](https://networkx.github.io/documentation/networkx-1.10/reference/classes.digraph.html?highlight=digraph#iterating-over-nodes-and-edges) I changed `graph.edge` to `graph.edges` on line 308 and the error mentioned above goes away, but a new error arises: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 349, in text_rank
    graph = build_graph(json_iter(path))
  File "/home/user/.local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 308, in build_graph
    graph.edges[pair[0]][pair[1]]["weight"] += 1.0
  File "/home/user/.local/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 929, in __getitem__
    u, v = e
ValueError: too many values to unpack (expected 2)
```

**Comment by clayms** [comment]
some more info [here](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html)

**Comment by clayms** [comment]
I changed line 308 from 
https://github.com/ceteri/pytextrank/blob/181ea41375d29922eb96768cf6550e57a77a0c95/pytextrank/pytextrank.py#L308

to `graph.edges[0,1]["weight"] += 1.0`

and everything works great.

**Comment by krtrth** [comment]
replace edge with adj it will work
