### ISSUE TITLE
Bug: [E002] Can't find factory for 'textrank' for language English (en)

### ISSUE THREAD

**Issue by repodiac** [DerwenAI/pytextrank#196]
Hi,

I did run the example from the [pypi website](https://pypi.org/project/pytextrank/) and tried both current `spacy 3.1.2` as well as `3.0` in combination with model `en_core_web_sm` (via pip install):

```
import spacy
import pytextrank

# example text
text = "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("en_core_web_sm")

# add PyTextRank to the spaCy pipeline
nlp.add_pipe("textrank")
doc = nlp(text)

# examine the top-ranked phrases in the document
for phrase in doc._.phrases:
    print(phrase.text)
    print(phrase.rank, phrase.count)
    print(phrase.chunks)
```

However, the error I get is (probably) the same as #192 (I initially tried with the German model `de_core_news_sm` but even the English model does not work and gives the **same** error!):

```
ValueError: [E002] Can't find factory for 'textrank' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, parser, beam_parser, entity_linker, ner, beam_ner, entity_ruler, lemmatizer, tagger, morphologizer, senter, sentencizer, textcat, textcat_multilabel, en.lemmatizer
```

To me, it seems there is an incompatibility or the example is outdated and not adapted to spacy 3.x???

**Comment by phongtnit** [comment]
I had same error :(

**Comment by ceteri** [comment]
Thank you very much @repodiac and @phongtnit 
We're running tests with `spaCy` version 3.1.3 and not able to reproduce this error.

Could you provide us with more information about your platform and a full trace of the error?

**Comment by repodiac** [comment]
Hi,

I did as follows:
1. Install virtualenv and switch to activate (in my case, I use Python 3.8.10 under Ubuntu)
2. `pip install spacy pytextrank`
3. Save your example script from [above](https://github.com/DerwenAI/pytextrank/issues/196#issue-991366566) i.e. **your** website to p.py
4. Run `python p.py`

Result:
```
Traceback (most recent call last):
  File "p.py", line 8, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/tmp/venv/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/tmp/venv/lib/python3.8/site-packages/spacy/util.py", line 354, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

```

**Comment by ceteri** [comment]
The setup and code in this gist works with a DE language model: https://gist.github.com/ceteri/e22a92e0a7f55b6d4121a323ce8108b4

Note that you want to use `nlp = spacy.load("de_core_news_sm")`
while in the code listed with the error it uses `nlp = spacy.load("de_core_web_sm")`
