### ISSUE TITLE
pos_family = tok_tag.lower()[0] IndexError: string index out of range

### ISSUE THREAD

**Issue by sayak1711** [DerwenAI/pytextrank#26]
Hi
I am getting the following error while running pytextrank on around 300+ documents:
`Traceback (most recent call last):
  File "........../TextRank/driver_pytxtrank.py", line 10, in <module>
    for graf in pytextrank.parse_doc(pytextrank.json_iter(path_stage0)):
  File ".........../anaconda3/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 263, in parse_doc
    grafs, new_base_idx = parse_graf(meta["id"], graf_text, base_idx)
  File ".................../anaconda3/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 225, in parse_graf
    pos_family = tok_tag.lower()[0]
IndexError: string index out of range`

Also I encountered a error which said that it can't handle text having more than 1000000 characters.
This was the error:
`Traceback (most recent call last):
  File "........../TextRank/driver_pytxtrank.py", line 10, in <module>
    for graf in pytextrank.parse_doc(pytextrank.json_iter(path_stage0)):
  File "........../anaconda3/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 261, in parse_doc
    grafs, new_base_idx = parse_graf(meta["id"], graf_text, base_idx)
  File ".........../anaconda3/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 193, in parse_graf
    doc = spacy_nlp(graf_text)
  File ".........../anaconda3/lib/python3.6/site-packages/spacy/language.py", line 345, in __call__
    max_length=self.max_length))
ValueError: [E088] Text of length 1926491 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the nlp.max_length limit. The limit is in number of characters, so you can check whether your inputs are too long by checking len(text).`

To fix that I made the following change to pytextrank.py:

if len(graf_text) >= 999999:
           graf_text = graf_text[:999999]
 grafs, new_base_idx = parse_graf(meta["id"], graf_text, base_idx)

which was followed by the before mentioned errors

**Comment by sayak1711** [comment]
This could be a issue with fix_hypenation or fix_microsoft function

**Comment by ohmjoh** [comment]
I changed the line 225 of pytextrank.py
from: pos_family = tok_tag.lower()[0]
to: pos_family = tok_tag.lower()
It worked for me.

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve these issues.
