### ISSUE TITLE
at stage2.py

### ISSUE THREAD

**Issue by krtrth** [DerwenAI/pytextrank#29]
while running i got this error

`Traceback (most recent call last):
File "/newvolume/var/www/krackin_ai/krackin_ai/app/Scripts/stage2.py", line 17, in <module>
render_ranks(graph, ranks)
File "/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py", line 336, in render_ranks
write_dot(graph, ranks, path=dot_file)
File "/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py", line 327, in write_dot
with open(path, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'graph.dot'`

**Comment by ceteri** [comment]
Probably the simplest way to resolve that would be to provide a different file name?

Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve these issues.
